### ISSUE TITLE
MyHandler has no attribute 'headers'

### ISSUE THREAD

**Issue by micsthepick** [bocajspear1/honeyhttpd#12]
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/lib/python3.11/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/lib/python3.11/http/server.py", line 414, in handle_one_request
    if not self.parse_request():
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/server.py", line 316, in parse_request
    self.send_error(
  File "/home///honeyhttpd/honeyhttpd/lib/server.py", line 58, in send_error
AttributeError: 'MyHandler' object has no attribute 'headers'
```

**Comment by bocajspear1** [comment]
Should be fixed in latest commit. Let me know if you can verify and I'll close the issue. Thanks!

**Comment by micsthepick** [comment]
LGTM, you may close.
